import React from 'react';

export default function Head() {
  return (
    <>
      <title>Akacords</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
